spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/personal_finances
    username: your_username
    password: your_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  server:
    port: 8080